version: '3'

services:
    postgres:
        build:
            context: https://github.com/M4MController/controller-web.git
            dockerfile: Dockerfile-db
        environment:
            POSTGRES_USER: "m4m"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "m4m"
        restart: always
    frontend:
        build:
            context: https://github.com/M4MController/frontend.git
            dockerfile: Dockerfile
            args:
                MODE: lite
                GOOGLE_API_MAPS_KEY: google_api_maps_key
        ports:
            - 80:80
        depends_on:
            - backend
        restart: always
    backend:
        build:
            context: https://github.com/M4MController/controller-web.git
            dockerfile: Dockerfile
        depends_on:
            - postgres
        restart: always
    # todo: move to sensor repo
    sensor_obd_gps:
        build:
            context: https://github.com/M4MController/controller-web.git
            dockerfile: sensors_polling/Dockerfile
        depends_on:
            - postgres
        restart: always
        privileged: true
        environment:
            SEND_TO_SERVER: ""
            USE_STUBS: ""
            DEVICE: "/dev/obd"
        volumes:
            - "/dev/obd:/dev/obd"
    radio:
        build:
            context: https://github.com/M4MController/controller-radio.git
            dockerfile: Dockerfile
        volumes:
            - "/dev/xbee:/dev/xbee"
        environment:
            DB_URI: postgresql://m4m:12345@postgres:5432/m4m
            DEVICE: "/dev/xbee"
            USE_STUBS: ""
        depends_on:
            - postgres
        privileged: true
        restart: always
