version: '3'

services:
    database:
        image: registry.meter4.me:25410/controller-database
        environment:
            POSTGRES_USER: "m4m"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "m4m"
        restart: always
    frontend:
        image: registry.meter4.me:25410/controller-frontend
        ports:
            - 80:80
        depends_on:
            - backend
        restart: always
    backend:
        image: registry.meter4.me:25410/controller-backend
        depends_on:
            - database
        restart: always
    sensor-obd:
        image: registry.meter4.me:25410/sensor-obd
        depends_on:
            - backend
        restart: always
        privileged: true
        environment:
            URI: http://backend:5000
            DEVICE: "/dev/obd"
        volumes:
            - "/dev/obd:/dev/obd"
    sensor-gps:
        image: registry.meter4.me:25410/sensor-gps
        depends_on:
            - backend
        restart: always
        privileged: true
        environment:
            URI: http://backend:5000
    radio:
        image: registry.meter4.me:25410/controller-radio
        volumes:
            - "/dev:/dev"
        environment:
            DB_URI: postgresql://m4m:12345@database:5432/m4m
            DEVICE: "/dev/serial0"
        depends_on:
            - database
        privileged: true
        restart: always
    synchronizer:
        image: registry.meter4.me:25410/controller-backend
        environment:
            DB_URI: postgresql://m4m:12345@database:5432/m4m
        depends_on:
            - database
        restart: always
