version: '3'

services:
    postgres:
        image: postgres
        ports:
            -  5432:5432
        volumes:
            - ./postgres:/var/lib/postgresql/data
        restart: always
    frontend:
        environment:
            GOOGLE_API_MAPS_KEY: google_api_maps_key
        build:
            context: github.com/m4mcontroller/frontend
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
        restart: always
