version: '3'

services:
    database:
        build:
            context: https://github.com/M4MController/controller-web.git
            dockerfile: Dockerfile-db
        environment:
            POSTGRES_USER: "m4m"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "m4m"
        restart: always
    frontend:
        build:
            context: https://github.com/M4MController/frontend.git
            dockerfile: Dockerfile
            args:
                MODE: lite
                GOOGLE_API_MAPS_KEY: google_api_maps_key
        ports:
            - 80:80
        depends_on:
            - backend
        restart: always
    backend:
        build:
            context: https://github.com/M4MController/controller-web.git
            dockerfile: Dockerfile
        depends_on:
            - database
        restart: always
    sensor-obd:
        build:
            context: https://github.com/M4MController/sensor-obd.git
            dockerfile: Dockerfile
        depends_on:
            - backend
        restart: always
        privileged: true
        environment:
            URI: http://backend:5000
            USE_STUBS: ""
            DEVICE: "/dev/obd"
        volumes:
            - "/dev/obd:/dev/obd"
    sensor-gps:
        build:
            context: https://github.com/M4MController/sensor-gps.git
            dockerfile: Dockerfile
        depends_on:
            - backend
        restart: always
        privileged: true
        environment:
            USE_STUBS: ""
            URI: http://backend:5000
    radio:
        build:
            context: https://github.com/M4MController/controller-radio.git
            dockerfile: Dockerfile
        volumes:
            - "/dev/xbee:/dev/xbee"
        environment:
            DB_URI: postgresql://m4m:12345@database:5432/m4m
            DEVICE: "/dev/xbee"
            USE_STUBS: ""
        depends_on:
            - database
        privileged: true
        restart: always
    synchronizer:
        build:
            context: https://github.com/M4MController/controller-sync.git
            dockerfile: Dockerfile
        environment:
            DB_URI: postgresql://m4m:12345@database:5432/m4m
        depends_on:
            - database
        restart: always
